service_confirm:
  path:       /confirm
  methods:    [POST]
  controller: App\Controller\Service\ConfirmController
service_offers:
  path:       /offers
  methods:    [GET]
  controller: App\Controller\Service\OffersController